### ISSUE TITLE
Проблема с ихоровым топором

### ISSUE THREAD

**Issue by linkinkov** [gamerforEA/ThaumicTinkerer-FakePlayers#1]
пробуждённый ихоровый топор в режиме "дерево". Если заприватить низ дерева, затем попробовать этим топором срубить ту часть, которая не в привате, то срубится всё дерево, но сервер ляжет, т.к срубится блок, который был в привате.

Вообще с ихоровым топором много проблем в плане нагрузки на сервер, когда рубится дерево, без ивентов проблем нет.

**Comment by gamerforEA** [comment]
Я смотрел код, но так и не смог понять, из-за чего возникает эта проблема.

**Comment by linkinkov** [comment]
Ну стоило попытаться написать, если сможете пофиксить, было бы замечательно

**Comment by 008** [comment]
отключите этот режим в коде и все.

**Comment by linkinkov** [comment]
Какой режим? Режим дерево? Так отпадает большая функциональность

**Comment by gamerforEA** [comment]
Спустя долгие годы пишу ответ. Проблема заключалась в бесконечном цикле. Исправлено в 2017 году. :)
https://github.com/gamerforEA/ThaumicTinkerer-FakePlayers/commit/e680f5f57d9dace907c5dbd266f1439d2e943c25
