### ISSUE TITLE
ThaumicTinkerer 510 Original Download for clients?

### ISSUE THREAD

**Issue by djoveryde** [gamerforEA/ThaumicTinkerer-FakePlayers#2]
Hi, I have added thaumicTinkerer to my server however players cannot connect to it as the latest version i can find is only 164, any ideas how I find the original 510 version to add into the client loader?

**Comment by gamerforEA** [comment]
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/
