### ISSUE TITLE
Release use in modpacks

### ISSUE THREAD

**Issue by LordPinkerton** [gamerforEA/ThaumicTinkerer-FakePlayers#6]
I would like to use the github release version of this mod in a modpack via Curse. However, since the versions on github are not on the Curse network, to add them as an approved third party mod, they require some form of MIT/GPL style declaration that the mod may be used in modpacks without restriction. Would it be possible to add such a statement at the landing of this repository for this purpose? Thank you.

**Comment by gamerforEA** [comment]
https://github.com/gamerforEA/ThaumicTinkerer-FakePlayers/commit/65090adffc1cce5ec0ce06b14f261e6b1381229c
